### ISSUE TITLE
Automated process to build and deploy docs

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/cil#101]
I started cleaning the docs in #57, but they have once again become outdated because manual building and publishing to `www2.in.tum.de` is needed.
We should automate this step (e.g. using Github actions) to ensure up-to-date documentation being available.

**Comment by sim642** [comment]
> publishing to `www2.in.tum.de` is needed

Why not just deploy to this repository's GitHub Pages? That's what most modern OCaml packages on GitHub do.

**Comment by sim642** [comment]
There's even a setup-ocaml subaction for directly doing that: https://github.com/ocaml/setup-ocaml#deploy-doc.

**Comment by michael-schwarz** [comment]
> Why not just deploy to this repository's GitHub Pages? 

Sure!

> There's even a setup-ocaml subaction for directly doing that: https://github.com/ocaml/setup-ocaml#deploy-doc.

At first glance, that doesn't seem to be built for our strange HEVEA / ocamldoc combination though, I think we need to write our own action for that.

**Comment by sim642** [comment]
> At first glance, that doesn't seem to be built for our strange HEVEA / ocamldoc combination though, I think we need to write our own action for that.

True, I forgot about the HEVEA stuff. It's fairly easy to just upload anything to GitHub Pages (really commit to `gh-pages` branch) from Actions though.

**Comment by michael-schwarz** [comment]
I have now setup an automatic deployment to https://goblint.github.io/cil/.
What this also means is that we probably should get more serious about keeping consistent version numbers.
