### ISSUE TITLE
Dynlink.error when compiling cil with dune following goblint

### ISSUE THREAD

**Issue by ghost** [goblint/cil#126]
**I just start learning dune, and try to update  CIL (version 1.7.3) using dune. I follow the way goblint (version 2.0) does., but meet a problem. After dune build @install && dune install,  I call cilly, and there is an error:**
 
The following are the arguments of the Cilly process
Error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"tianshu-cil/_opam/lib/ocaml/dynlink.cmxs: cannot open shared object file: No such file or directory\")")
Fatal error: exception TianshuCil__Errormsg.Error

I find dynlink.cmxs does not exist in opam lib, but goblint-cil has no problem.
Could you do me a favor?

Here is my source code repository https://github.com/gsfan15/tianshu-cil

**Comment by sim642** [comment]
I don't have a definite answer for you, but we have some small changes to the CIL feature loading mechanism that may be related: https://github.com/goblint/cil/commits/develop/src/feature.ml.

Just wondering, is there a reason you're trying to redo this instead of just using goblint-cil?

**Comment by ghost** [comment]
Thanks very much! This has really help me. I have consider using goblint-cil, since it has been developed well thanks to your research group. However, I need to finish a project as soon as possible. So sad, hhh.

**Comment by michael-schwarz** [comment]
Closing this as the question seems to be answered. If you have any more questions, feel free to open a new issue!
