### ISSUE TITLE
Unbound module CIL

### ISSUE THREAD

**Issue by nguyenthanhvuh** [goblint/cil#127]
Hello, I have a project that uses the original CIL and I can compile file using something like
```
ocamlopt                        -I ../../EXTERNAL_FILES/cil/_build/src -I ../../EXTERNAL_FILES/cil/_build/src/ext -I ../../EXTERNAL_FILES/cil/_build/src/frontc -I ../../EXTERNAL_FILES/cil/_build/src/ocamlutil  -c common.ml
```

I have successfully built goblint-cil using dune as given in the instruction, but now I am not sure how to properly link to goblint-cil library.  E.g., doing the follow gives error
```
ocamlopt                        -I /usr/lib/ocaml/goblint-cil/  -c common.ml
File "common.ml", line 1, characters 5-8:
1 | open Cil
         ^^^
Error: Unbound module Cil
```

I am probably missing something really simple here.

**Comment by sim642** [comment]
Starting from version 2.0.0 we wrap our library into the `GoblintCil` module to reduce naming conflicts.

**Comment by nguyenthanhvuh** [comment]
Thanks,  changing to `GoblintCil` works,  but now at the end of my build I have this other error about `Z` and `Big_int_Z`  

```
ocamlopt                        -I /usr/lib/ocaml/goblint-cil/  -c common.ml
ocamlopt                        -I /usr/lib/ocaml/goblint-cil/  -c instr.ml
ocamlopt                        -I /usr/lib/ocaml/goblint-cil/  -o instr.exe unix.cmxa str.cmxa nums.cmxa goblintCil.cmxa common.cmx instr.cmx
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Z referenced from /usr/lib/ocaml/goblint-cil/goblintCil.cmxa(GoblintCil__Cil)
         Big_int_Z referenced from /usr/lib/ocaml/goblint-cil/goblintCil.cmxa(GoblintCil__Cilint)

```

**Comment by sim642** [comment]
Our fork has been updated to use Zarith instead of Num, so you'll have to install and link that instead.

**Comment by nguyenthanhvuh** [comment]
I got it to work. Thank you for the quick replies.
