### ISSUE TITLE
where are the libraries after opam install goblint-cil?

### ISSUE THREAD

**Issue by nguyenthanhvuh** [goblint/cil#131]
I have successfully install via `opam install goblint-cil`,  now I want to compile Ocaml file with goblint-cil (i.e., files with `open GoblintCil`) but I cannot find where the installed libraries are,  should it be install somewhere like `/usr/lib/ocaml/goblint-cil/` ?

**Comment by sim642** [comment]
Opam installs packages in the current opam switch. This can be local (an `_opam` directory somewhere where you might have locally created it) or global (e.g. `~/.opam/4.14.1`). Relative to that, goblint-cil installs into `lib/goblint-cil`.

There shouldn't be need to actually know the precise path and library file names. Simply depending on the `goblint-cil` library in dune (or via some other ocamlfind mechanism), everything should be found and used automatically.

**Comment by nguyenthanhvuh** [comment]
got it, thanks!

**Comment by michael-schwarz** [comment]
Happy to help! Feel free to reopen if any other questions come up 😊
