### ISSUE TITLE
Transformation `assert` causes GNU inline merging problems with `-O3`

### ISSUE THREAD

**Issue by J2000A** [goblint/cil#149]
During the [implementation for my bachelor thesis](https://github.com/goblint/bench/pull/58) about generating test cases for the incremental analysis I encountered a problem with the flag `-O3`. Possibly some merging problems with GNU inline? @stilscher

 Reproduce by:
 `echo "main(){}" > input.c`
`./goblint input.c --enable trans.goblint-check --set trans.activated '["assert"]' --set pre.cppflags[+] -O3`
`./goblint transformed.c --set pre.cppflags[+] -O3 --enable incremental.save`
`./goblint transformed.c --set pre.cppflags[+] -O3 --enable incremental.load`

This results in the error:
`Fatal error: exception Failure("there can only be one definition and one declaration per global")`

Output of `cat transformed.c | grep pthread_equal`:
```
__inline extern int ( __attribute__((__leaf__, __gnu_inline__)) pthread_equal)(pthread_t __thread1 ,
__inline extern int ( __attribute__((__leaf__, __gnu_inline__)) pthread_equal)(pthread_t __thread1 ,
__inline extern int ( __attribute__((__leaf__, __gnu_inline__)) pthread_equal)(pthread_t __thread1 ,
__inline extern int ( __attribute__((__leaf__, __gnu_inline__)) pthread_equal)(pthread_t __thread1 ,
```
vs when not using `--set pre.cppflags[+] -O3`:
```
extern int ( __attribute__((__leaf__)) pthread_equal)(pthread_t __thread1 ,
```

**Comment by michael-schwarz** [comment]
Is this only an issue for files that have been transformed using Goblint? If yes, I would once again suggest to move the issue over to the analyzer repository.

**Comment by J2000A** [comment]
Hey @michael-schwarz,
yeah you are right this also should go to the analyzer repo 👍

**Comment by J2000A** [comment]
I will repost this in the analyzer repo

**Comment by michael-schwarz** [comment]
I'll move it instead!
