### ISSUE TITLE
Remove package guard against ARM64

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/cil#164]
@DrMichaelPetter tested on MacOS Sonoma 14.3 (M1 Pro CPU) today, and CIL works fine on there. We should remove the package guard in OPAM to facilitate students working with it and release a new goblint-cil version.

**Comment by sim642** [comment]
#154 needs to be handled for this.

**Comment by sim642** [comment]
The test from #154 doesn't seem to fail in GitHub CI on OSX arm64 now. I wonder if the opam-repository CI machines are somehow different.

@DrMichaelPetter Do all CIL tests pass on your M1 Mac? CIL may build and install fine regardless, because opam doesn't usually run tests for packages.

**Comment by DrMichaelPetter** [comment]
dune test runs through without hickups on my M1 Mac

**Comment by sim642** [comment]
I've relaxed the availability to allow for `arm64` in 8f9b0c660a020308b12e15276ad9a82cc9a64c9f.
