### ISSUE TITLE
Variable "hidden" parse errors in SV-COMP SoftwareSystems

### ISSUE THREAD

**Issue by sim642** [goblint/cil#18]
In my own run of Goblint on SV-COMP SoftwareSystems category, Goblint crashed with `Frontc.ParseError` exception on the following benchmarks:

- [ ] ldv-consumption/32_7a_cilled_linux-3.8-rc1-drivers--vfio--pci--vfio-pci.ko-main.cil.out.i (line 6196)
- [ ] ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--vfio--pci--vfio-pci.ko-entry_point.cil.out.i (line 140207)
- [ ] ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--vfio--pci--vfio-pci.ko-entry_point.cil.out.i (line 139889)

All three lines are the assignment `hidden = 0`. Minimal crashing example:

```c
int main()
{
    int hidden;
    hidden = 0;
    return 0;
}
```

Seems like CIL is parsing `hidden` as some kind of GCC-specific attribute which causes parsing to fail when it's just used as a variable name in an assignment...

**Comment by michael-schwarz** [comment]
This was introduced in https://github.com/goblint/cil/commit/6712e5a3714679108941e4b9be8a4879bc49f335 that added `hidden` as an attribute.
Do you recall why this was necessary, @vogler ?

The GCC manual does not say anything about an attribute `hidden` except `__attribute__((__visibility__("hidden")))`.

**Comment by vogler** [comment]
I guess it was for analyzing the standard library. We had problems with glibc and then continued with musl libc, so it was probably used there.

**Comment by michael-schwarz** [comment]
Given that `gcc` accepts neither `hidden int x;` , `__hidden__ int x;`, nor `__visibility("hidden")__` as valid C and CIL handles `__attribute__((visibility("hidden"))) int x;` without these changes, I'd suggest undoing that change for now.

Opinions?

**Comment by vogler** [comment]
Ok, but keep the `_Complex`.

`ag '[^\.]hidden ' | wc -l` has 435 hits for musl libc.
It compiles with `cpp`, maybe `gcc` needs some flag to accept it.
Since it defines visibility, it's probably only used for globals/functions.

**Comment by michael-schwarz** [comment]
> Ok, but keep the _Complex.

Yes, of course, that's needed for C99 / C11 support.

> It compiles with cpp, maybe gcc needs some flag to accept it.
```
michael@michael-ThinkPad-X1-Carbon-6th:~/Downloads/musl-1.2.1$ grep -r "__visibility__" .
./src/include/features.h:#define hidden __attribute__((__visibility__("hidden")))
```
So hopefully the preprocessor should replace this with the expanded definition before CIL or Goblint get to see it. I'll include a test with this macro into the CIL regression tests.
