### ISSUE TITLE
Make build via `make` work again

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/cil#22]
Currently building via `make` (ocamlbuild) is broken, and only building via `dune build` works.

**Comment by michael-schwarz** [comment]
Now only the `make test` target is broken.

**Comment by vogler** [comment]
What's the issue/what broke it? Shouldn't have anything to do with the missing dependencies above.

**Comment by michael-schwarz** [comment]
> What's the issue/what broke it? Shouldn't have anything to do with the missing dependencies above.

Apparently, when I renamed the `findlib` package to match the name of the `opam` package (`goblint-cil` vs. `cil`) I was not thorough enough and missed a couple of places. I now have tests via `make test` almost working again, one example is still broken.
For this example, I had to adapt the include path for it to work with `dune runtest`, and apparently borke it for `make test` while doing that.
