### ISSUE TITLE
Repair CI for OS X

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/cil#50]
The CI for Mac currently fails with message `opam: unknown command `depext'.`.

Constantly having failing tests means it is easy to miss if another test newly fails.

**Comment by vogler** [comment]
Some notes:

macos: opam/2.1.0 https://github.com/goblint/cil/runs/3874800641#step:4:1010
ubuntu: opam/2.0.8 https://github.com/goblint/cil/runs/3874800980#step:4:61

https://opam.ocaml.org/blog/opam-2-1-0/#Seamless-integration-of-System-dependencies-handling-a-k-a-quot-depexts-quot

cil is still using the v1 action:
https://github.com/goblint/cil/blob/c16dddf74f6053a8b3fac07ca2feff18d4d56964/.github/workflows/tests.yml#L46
goblint is using the v2 action:
https://github.com/goblint/analyzer/blob/0f0ffcd4b4b2292b1525a5c17aadd330d66faced/.github/workflows/unlocked.yml#L39

**Comment by vogler** [comment]
Fixed by upgrading to `setup-ocaml@v2` (https://github.com/goblint/cil/commit/b1f8137c3d284295ecba2ca7a6f29af014c9cadc) which uses opam/2.0.9 on macos.

Previous comments on v1 vs. v2 (mainly caching): https://github.com/goblint/analyzer/pull/296

**Comment by vogler** [comment]
Before https://github.com/goblint/cil/commit/33b13e24cf4bf09eab2a2a993f5ae024bbb2a8ac all but 4.04.2 worked.
After, all macos suddenly fail: `Package zarith is already installed` https://github.com/goblint/cil/runs/3875924530#step:9:121
Finicky CI... Maybe some issue with the cache.

**Comment by vogler** [comment]
Fixed by https://github.com/goblint/cil/commit/24ffb6cb593c9f9119e7283c919cfa3167a161e4 which removed the old cache action (`setup-ocaml@v2` caches as well).
