### ISSUE TITLE
C99 fixed-width integer and floating-point types

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/cil#8]
When running tests such as `testrun/math1` on a machine with a newer version of glibc, we produce a parse error, that seems to be related to the headers using the `float128` type.

We encountered this not just with toy programs, but also with real-world examples.

Find some way of still being able to parse these headers, probably by introducing a new `typ` for `float128`. On the Goblint side of things, we can just treat it (almost) like normal floats as we don't do anything for them anyway.

Related links:
- https://github.com/samee/obliv-c/issues/48 (other project using CIL that has this problem)
- https://github.com/NixOS/nixpkgs/commit/7f8bc042cc66682af06f6828bb4762af1e7b75e4 (patch for the lexer & parser to handle `float128` and `complex`)

**Comment by vogler** [comment]
That should be enough to parse those things, but I wonder whether we need all of them in `typeSpecifier`.
What's the difference between `__int64` and `int64_t` or `__float128` and `Float128`? The former are probably only extensions, while the latter were added in C99, see https://en.wikipedia.org/wiki/C_data_types#Fixed-width_integer_types. Should add all those to the lexer/parser as well, I guess.
At least those fixed width types are unambiguous. What we do for the more common `int, long, float, double` is another problem. We just assume they have the size of the machine CIL was built on, which might not be the case for the environment the analyzed program will run in.

`_build/machdep.ml`:
~~~ocaml
let gcc = {
(* Generated by code in src/machdep-ml.c *)
	 version_major    = 9;
	 version_minor    = 2;
	 version          = "9.2.0";
	 sizeof_short          = 2;
	 sizeof_int            = 4;
	 sizeof_bool           = 1;
	 sizeof_long           = 8;
	 sizeof_longlong       = 8;
	 sizeof_ptr            = 8;
	 sizeof_float          = 4;
	 sizeof_double         = 8;
	 sizeof_longdouble     = 16;
	 sizeof_void           = 1;
	 sizeof_fun            = 1;
	 size_t                = "unsigned long";
	 wchar_t               = "int";
	 alignof_short         = 2;
	 alignof_int           = 4;
	 alignof_bool          = 1;
	 alignof_long          = 8;
	 alignof_longlong      = 8;
	 alignof_ptr           = 8;
	 alignof_enum          = 4;
	 alignof_float         = 4;
	 alignof_double        = 8;
	 alignof_longdouble    = 16;
	 alignof_str           = 1;
	 alignof_fun           = 1;
	 alignof_aligned       = 16;
	 char_is_unsigned      = false;
	 const_string_literals = true;
	 underscore_name       = true;
	 __builtin_va_list     = true;
	 __thread_is_keyword   = true;
	 little_endian         = true;
}
~~~

So on my machine `long double` == `__float128` == `Float128`.

**Comment by vogler** [comment]
Ok, those `int64_t` etc. are defined in <inttypes.h>, so they don't need to be added.
However, for floats there's apparently no such header and the types from [here](https://en.wikipedia.org/wiki/C_data_types#Additional_floating-point_types) should be added. TODO how many? N=8,16,32,64,128?
https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html
https://stackoverflow.com/questions/2524737/fixed-size-floating-point-types

**Comment by michael-schwarz** [comment]
I added `_Float128` for now, so I can use the `math1` example to see which other changes are required.

Right now, we get `Error: Invalid combination of type specifiers`.

**Comment by michael-schwarz** [comment]
With https://github.com/goblint/cil/pull/10, https://github.com/goblint/cil/pull/60, https://github.com/goblint/cil/pull/68, and https://github.com/goblint/cil/pull/49 everything here seems to be covered.

The fixed-width integer types seem to be just type-defed to more usual types in GCC as evidenced by https://github.com/goblint/cil/commit/9e3b8c6f1d114486c294260413d1317d2623f784 (at least for Linux).

I'll wait and see what OS X CI says, but otherwise I think we can close this issue.
